export const aliases: Record<string, string[]> = {
  meta: ["Command", "Control", "Ctrl"],
  control: ["Ctrl"],
  cmd: ["Command"],
  windows: ["Win"],
  "⌘": ["Command"],
  "⌥": ["Alt"],
  capslock: ["Caps", "Caps Lock"],
  space: ["", " "],
  os: ["windows", "super", "win"],
  arrowleft: ["left"],
  arrowright: ["right"],
  arrowup: ["up"],
  arrowdown: ["down"],
  pageup: ["pgup"],
  pagedown: ["pgdn", "pgdown"],
  escape: ["esc"],
};
