export const layout: { label: string; width: number }[][] = [
  [
    { label: "Esc", width: 1 },
    { label: "1", width: 1 },
    { label: "2", width: 1 },
    { label: "3", width: 1 },
    { label: "4", width: 1 },
    { label: "5", width: 1 },
    { label: "6", width: 1 },
    { label: "7", width: 1 },
    { label: "8", width: 1 },
    { label: "9", width: 1 },
    { label: "0", width: 1 },
    { label: "-", width: 1 },
    { label: "=", width: 1 },
    { label: "Backspace", width: 2 },
    { label: "Home", width: 1 },
  ],
  [
    { label: "Tab", width: 1.5 },
    { label: "Q", width: 1 },
    { label: "W", width: 1 },
    { label: "E", width: 1 },
    { label: "R", width: 1 },
    { label: "T", width: 1 },
    { label: "Y", width: 1 },
    { label: "U", width: 1 },
    { label: "I", width: 1 },
    { label: "O", width: 1 },
    { label: "P", width: 1 },
    { label: "[", width: 1 },
    { label: "]", width: 1 },
    { label: "\\", width: 1.5 },
    { label: "PgUp", width: 1 },
  ],
  [
    { label: "Caps Lock", width: 1.75 },
    { label: "A", width: 1 },
    { label: "S", width: 1 },
    { label: "D", width: 1 },
    { label: "F", width: 1 },
    { label: "G", width: 1 },
    { label: "H", width: 1 },
    { label: "J", width: 1 },
    { label: "K", width: 1 },
    { label: "L", width: 1 },
    { label: ";", width: 1 },
    { label: "'", width: 1 },
    { label: "Enter", width: 2.25 },
    { label: "PgDn", width: 1 },
  ],
  [
    { label: "Shift", width: 2.25 },
    { label: "Z", width: 1 },
    { label: "X", width: 1 },
    { label: "C", width: 1 },
    { label: "V", width: 1 },
    { label: "B", width: 1 },
    { label: "N", width: 1 },
    { label: "M", width: 1 },
    { label: ",", width: 1 },
    { label: ".", width: 1 },
    { label: "/", width: 1 },
    { label: "Shift", width: 1.75 },
    { label: "Up", width: 1 },
    { label: "End", width: 1 },
  ],
  [
    { label: "Ctrl", width: 1.25 },
    { label: "Win", width: 1.25 },
    { label: "Alt", width: 1.25 },
    { label: "", width: 6.25 },
    { label: "Alt", width: 1 },
    { label: "Fn", width: 1 },
    { label: "Ctrl", width: 1 },
    { label: "Left", width: 1 },
    { label: "Down", width: 1 },
    { label: "Right", width: 1 },
  ],
];
